image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terraform Init & Apply
    command: |
      terraform init
      # We use -auto-approve to avoid interactive prompt in automation
      # Note: In a real environment, you might want to review the plan first
      terraform apply -auto-approve

ports:
  - port: 5000
    onOpen: open-preview
    name: Web Interface
  - port: 5001
    onOpen: ignore
    name: Auth Service
  - port: 5002
    onOpen: ignore
    name: User Service
  - port: 5003
    onOpen: ignore
    name: Orders Service
  - port: 5004
    onOpen: ignore
    name: Gateway
